### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mavogel** [mavogel/vis-lab#7]
# Roadmap
## Must
- [ ] OAuth2 and [Security](http://cloud.spring.io/spring-cloud-security/)
- [ ] Feign Exception and 4xx HTTP status forwarding
- [ ] Consistent `ResponseEntity` return types

## Should
- [ ] Ribbon [Load-Balancing](https://spring.io/guides/gs/client-side-load-balancing/)
- [ ] Integration Testing 
- [ ] Logging

## Could
- [ ] Config Service
- [ ] Polyglot Perisistency
